In [1]:
from cmath import *
import numpy as np
from scipy.linalg import expm, sinm, cosm, logm
from qiskit.quantum_info.synthesis.two_qubit_decompose import * 
from scipy.linalg import sqrtm 

In [2]:
A = np.matrix(10*np.random.rand(3,3))  # random matriz 3x3
A = (A + A.T)/2  # matriz simetrica

D = np.matrix('0.3125 0; 0 0.75')
P = 1/sqrt(2)*np.matrix('1 0; 0 1')

A = P*D*P.I
#print(D)
#print(P)
#print(A)
#A=matrix = [[1, 3], [3, 2]]

U = np.matrix(expm(1j*A))

In [3]:
#m_90 = sqrtm(U)
#theta,phi,lambd = euler_angles_1q(U)  

theta,phi,lambd = 2*pi,pi/6,pi/4
print(theta,phi,lambd)

U1 = np.matrix([[cos(theta/2),-exp(1j*lambd)*sin(theta/2)],
           [exp(1j*phi)*sin(theta/2),exp(1j*lambd+1j*phi)*cos(theta/2)]])

theta,phi,lambd = euler_angles_1q(U1)
U1,theta,phi,lambd

6.283185307179586 0.5235987755982988 0.7853981633974483


(matrix([[-1.00000000e+00-0.00000000e+00j,
          -8.65956056e-17-8.65956056e-17j],
         [ 1.06057524e-16+6.12323400e-17j,
          -2.58819045e-01-9.65925826e-01j]]),
 2.4492935982947064e-16,
 -2.6179938779914944,
 -2.3561944901923453)

In [14]:
H=-1j*logm(U1)
w, v = np.linalg.eigh(H)
H,w

(array([[-3.14159265e+00+2.70616862e-16j,  1.71858109e-17-1.30539194e-16j],
        [ 0.00000000e+00-0.00000000e+00j, -1.83259571e+00+5.55111512e-16j]]),
 array([-3.14159265, -1.83259571]))

In [15]:
U2=np.matrix(expm(1j*H))
theta,phi,lambd = euler_angles_1q(U2)
U2,theta,phi,lambd

(matrix([[-1.00000000e+00-5.66553890e-16j,
          -8.65956056e-17-8.65956056e-17j],
         [ 0.00000000e+00+0.00000000e+00j,
          -2.58819045e-01-9.65925826e-01j]]),
 0.0,
 -2.48709418409192,
 -2.48709418409192)

In [60]:
U1-U2

matrix([[-2.22044605e-16+5.66553890e-16j,
         -6.16297582e-32+1.23259516e-32j],
        [ 1.06057524e-16+6.12323400e-17j,
         -2.77555756e-16-4.44089210e-16j]])

In [25]:
U3 = np.matrix([[cos(theta/2),-exp(1j*lambd)*sin(theta/2)],
           [exp(1j*phi)*sin(theta/2),exp(1j*lambd+1j*phi)*cos(theta/2)]])

theta,phi,lambd = euler_angles_1q(U3)
U3,theta,phi,lambd

(matrix([[ 1.00000000e+00-0.00000000e+00j,
           8.65956056e-17+8.65956056e-17j],
         [-1.06057524e-16-6.12323400e-17j,
           2.58819045e-01+9.65925826e-01j]]),
 2.449293598294707e-16,
 3.665191429188092,
 -2.3561944901923453)

In [9]:
U = np.matrix([[1, 0, 0, 0],[0, 1, 0, 0],
               [0,0,0.83948788+0.18918008j,  0.18918008+0.4729502j],[0,0,-0.18918008+0.4729502j ,  0.83948788-0.18918008j]])
U

matrix([[ 1.        +0.j        ,  0.        +0.j        ,
          0.        +0.j        ,  0.        +0.j        ],
        [ 0.        +0.j        ,  1.        +0.j        ,
          0.        +0.j        ,  0.        +0.j        ],
        [ 0.        +0.j        ,  0.        +0.j        ,
          0.83948788+0.18918008j,  0.18918008+0.4729502j ],
        [ 0.        +0.j        ,  0.        +0.j        ,
         -0.18918008+0.4729502j ,  0.83948788-0.18918008j]])

In [41]:
#decompose_two_qubit_product_gate(U3)
L = np.array([[-1.00000000e+00-0.00000000e+00j,-8.65956056e-17-8.65956056e-17j],[ 1.06057524e-16+6.12323400e-17j,
          -2.58819045e-01-9.65925826e-01j]], dtype=complex)

In [43]:
#twoq = TwoQubitBasisDecomposer(L)